[profile.default]
src        = 'contracts'
test       = 'tests'
libs       = ['modules']
out        = 'artifacts'
cache_path = 'cache'

solc_version   = '0.8.19'
evm_version    = 'london'
optimizer      = true
optimizer_runs = 4294967295

block_number    = 16557675
block_timestamp = 1675541000
gas_limit       = "18446744073709551615"

fuzz_runs   = 1000
verbosity   = 3
gas_reports = ['*']
