[profile.default]

# Project
src = 'contracts'
test = 'tests'
script = 'scripts'
libs = ['modules']
out = 'artifacts'
cache_path = 'cache'
broadcast = 'broadcast'

# Remappings
auto_detect_remappings = false
remappings = ['@crypt=.', '@forge=./modules/forge-std/src']

# Solidity
auto_detect_solc = true
offline = false

# Optimization
optimizer = true
optimizer_runs = 4294967295
via_ir = true

# Testing
ffi = false
verbosity = 3
block_number = 20000000
block_timestamp = 1717281407
chain_id = 31337
gas_limit = '18446744073709551615'
show_progress = true

# Fuzzing (deterministic)
seed = 69
fuzz_runs = 10_000

# Invariants
fail_on_revert = true
runs = 1_000
depth = 1_000
